import type {
  ProjectStage, CameraModel, LensType, FocalLength, CinemaAspectRatio,
  ShotType, CameraAngle, CameraMovement, LightingPreset, ShotFocus, CameraMechanism,
} from "@/lib/types";
import {
  SHOT_SIZE_ICONS, SHOT_FRAMING_ICONS, SHOT_ANGLE_ICONS,
  CAMERA_MOVEMENT_ICONS, SHOT_FOCUS_ICONS, CAMERA_MECHANISM_ICONS,
} from "@/lib/cinema-icons";

export const STAGE_ORDER: ProjectStage[] = ["narrative", "director_brief", "vision", "storyboard", "assembly", "export"];

export const STAGES: Record<ProjectStage, { label: string; description: string }> = {
  narrative: {
    label: "روایت",
    description: "داستان و ساختار محتوا",
  },
  director_brief: {
    label: "کارگردان هوشمند",
    description: "هویت بصری و DNA فیلم",
  },
  vision: {
    label: "دکوپاژ",
    description: "طراحی نماها و سکانس‌ها",
  },
  storyboard: {
    label: "استوری‌بورد",
    description: "تبدیل تصاویر به ویدیو",
  },
  assembly: {
    label: "مونتاژ",
    description: "ترکیب صدا و تصویر",
  },
  export: {
    label: "خروجی",
    description: "رندر و انتشار نهایی",
  },
};

export const VIDEO_STYLES = [
  { id: "cinematic", label: "سینمایی", icon: "Film" },
  { id: "documentary", label: "مستند", icon: "Camera" },
  { id: "commercial", label: "تبلیغاتی", icon: "Megaphone" },
  { id: "educational", label: "آموزشی", icon: "GraduationCap" },
  { id: "social", label: "شبکه‌های اجتماعی", icon: "Share2" },
  { id: "lego", label: "لگو", icon: "Box" },
  { id: "anime", label: "انیمه", icon: "PenTool" },
] as const;

export const ASPECT_RATIOS = [
  { id: "16:9", label: "افقی (16:9)", description: "یوتیوب، تلویزیون" },
  { id: "9:16", label: "عمودی (9:16)", description: "استوری، ریلز" },
  { id: "1:1", label: "مربعی (1:1)", description: "اینستاگرام" },
  { id: "4:5", label: "پرتره (4:5)", description: "فید اینستاگرام" },
] as const;

export const SHOT_TYPES = [
  { id: "extreme_close_up", label: "کلوزآپ شدید", labelEn: "ECU", description: "Extreme Close-Up", icon: SHOT_SIZE_ICONS.extreme_close_up },
  { id: "close_up", label: "کلوزآپ", labelEn: "CU", description: "Close-Up", icon: SHOT_SIZE_ICONS.close_up },
  { id: "medium_close_up", label: "مدیوم کلوزآپ", labelEn: "MCU", description: "Medium Close-Up", icon: SHOT_SIZE_ICONS.medium_close_up },
  { id: "medium", label: "نمای متوسط", labelEn: "MS", description: "Medium Shot", icon: SHOT_SIZE_ICONS.medium },
  { id: "medium_wide", label: "مدیوم واید", labelEn: "MFS", description: "Medium Wide", icon: SHOT_SIZE_ICONS.medium_wide },
  { id: "wide", label: "نمای باز", labelEn: "FS", description: "Wide Shot", icon: SHOT_SIZE_ICONS.wide },
  { id: "extreme_wide", label: "نمای بسیار باز", labelEn: "ELS", description: "Extreme Wide", icon: SHOT_SIZE_ICONS.extreme_wide },
  { id: "establishing", label: "استابلیشینگ", labelEn: "LS", description: "Establishing Shot", icon: SHOT_SIZE_ICONS.establishing },
  { id: "insert", label: "اینسرت", labelEn: "Insert", description: "Insert Shot", icon: SHOT_FRAMING_ICONS.insert },
  { id: "cutaway", label: "کات‌اوی", labelEn: "Cutaway", description: "Cutaway", icon: SHOT_FRAMING_ICONS.cutaway },
  { id: "two_shot", label: "دو نفره", labelEn: "Two-Shot", description: "Two-Shot", icon: SHOT_FRAMING_ICONS.two_shot },
  { id: "over_shoulder", label: "اور شولدر", labelEn: "OTS", description: "Over-the-Shoulder", icon: SHOT_FRAMING_ICONS.over_shoulder },
] as const;

export const CAMERA_MOVEMENTS = [
  { id: "static", label: "ثابت", labelEn: "Static", description: "بدون حرکت", icon: CAMERA_MOVEMENT_ICONS.static },
  { id: "pan", label: "پن", labelEn: "Pan", description: "چرخش افقی", icon: CAMERA_MOVEMENT_ICONS.pan },
  { id: "tilt", label: "تیلت", labelEn: "Tilt", description: "چرخش عمودی", icon: CAMERA_MOVEMENT_ICONS.tilt },
  { id: "dolly_in", label: "دالی جلو", labelEn: "Dolly In", description: "حرکت جلو", icon: CAMERA_MOVEMENT_ICONS.dolly_in },
  { id: "dolly_out", label: "دالی عقب", labelEn: "Dolly Out", description: "حرکت عقب", icon: CAMERA_MOVEMENT_ICONS.dolly_out },
  { id: "truck", label: "تراک", labelEn: "Truck", description: "حرکت جانبی", icon: CAMERA_MOVEMENT_ICONS.truck },
  { id: "crane", label: "کرین", labelEn: "Crane", description: "حرکت بالا/پایین", icon: CAMERA_MOVEMENT_ICONS.crane },
  { id: "handheld", label: "دستی", labelEn: "Handheld", description: "دوربین دستی", icon: CAMERA_MOVEMENT_ICONS.handheld },
  { id: "steadicam", label: "استدی‌کم", labelEn: "Steadicam", description: "Steadicam", icon: CAMERA_MOVEMENT_ICONS.steadicam },
  { id: "whip_pan", label: "ویپ پن", labelEn: "Whip Pan", description: "چرخش سریع", icon: CAMERA_MOVEMENT_ICONS.whip_pan },
  { id: "zoom", label: "زوم", labelEn: "Zoom", description: "بزرگ‌نمایی", icon: CAMERA_MOVEMENT_ICONS.zoom },
  { id: "push_in", label: "پوش این", labelEn: "Push In", description: "نزدیک شدن", icon: CAMERA_MOVEMENT_ICONS.push_in },
  { id: "pull_out", label: "پول اوت", labelEn: "Pull Out", description: "دور شدن", icon: CAMERA_MOVEMENT_ICONS.pull_out },
  { id: "arc", label: "آرک", labelEn: "Arc", description: "حرکت قوسی", icon: CAMERA_MOVEMENT_ICONS.arc },
] as const;

export const SHOT_FOCUS_OPTIONS = [
  { id: "deep_focus", label: "فوکوس عمیق", labelEn: "Deep Focus", description: "همه چیز واضح", icon: SHOT_FOCUS_ICONS.deep_focus },
  { id: "shallow_focus", label: "فوکوس کم‌عمق", labelEn: "Shallow Focus", description: "بوکه پس‌زمینه", icon: SHOT_FOCUS_ICONS.shallow_focus },
  { id: "soft_focus", label: "فوکوس نرم", labelEn: "Soft Focus", description: "تصویر مه‌آلود و رمانتیک", icon: SHOT_FOCUS_ICONS.soft_focus },
  { id: "tilt_shift_v", label: "تیلت‌شیفت عمودی", labelEn: "Tilt-Shift V", description: "مینیاتور عمودی", icon: SHOT_FOCUS_ICONS.tilt_shift_v },
  { id: "tilt_shift_h", label: "تیلت‌شیفت افقی", labelEn: "Tilt-Shift H", description: "مینیاتور افقی", icon: SHOT_FOCUS_ICONS.tilt_shift_h },
] as const;

export const CAMERA_MECHANISM_OPTIONS = [
  { id: "tripod", label: "سه‌پایه", labelEn: "Tripod", description: "ثابت و پایدار", icon: CAMERA_MECHANISM_ICONS.tripod },
  { id: "handheld", label: "دستی", labelEn: "Handheld", description: "حرکت ارگانیک", icon: CAMERA_MECHANISM_ICONS.handheld },
  { id: "gimbal", label: "گیمبال", labelEn: "Gimbal", description: "حرکت نرم و پایدار", icon: CAMERA_MECHANISM_ICONS.gimbal },
  { id: "steadicam", label: "استدی‌کم", labelEn: "Steadicam", description: "حرکت شناور", icon: CAMERA_MECHANISM_ICONS.steadicam },
  { id: "crane", label: "جرثقیل", labelEn: "Crane", description: "حرکت بالا/پایین", icon: CAMERA_MECHANISM_ICONS.crane },
  { id: "drone", label: "درون", labelEn: "Drone", description: "هوایی", icon: CAMERA_MECHANISM_ICONS.drone },
] as const;

export const CINEMATOGRAPHY_PRESETS = {
  lighting: [
    { id: "key_light", label: "نور اصلی", labelEn: "Key Light" },
    { id: "fill_light", label: "نور پر", labelEn: "Fill Light" },
    { id: "backlight", label: "نور پشت", labelEn: "Backlight" },
    { id: "high_key", label: "روشن (High-Key)", labelEn: "High-Key" },
    { id: "low_key", label: "تاریک (Low-Key)", labelEn: "Low-Key" },
    { id: "natural", label: "طبیعی", labelEn: "Natural" },
    { id: "golden_hour", label: "ساعت طلایی", labelEn: "Golden Hour" },
    { id: "blue_hour", label: "ساعت آبی", labelEn: "Blue Hour" },
    { id: "neon", label: "نئون", labelEn: "Neon" },
    { id: "silhouette", label: "سیلوئت", labelEn: "Silhouette" },
    { id: "chiaroscuro", label: "کیاروسکورو", labelEn: "Chiaroscuro" },
    { id: "soft_diffused", label: "نرم و پخش", labelEn: "Soft Diffused" },
    { id: "hard_dramatic", label: "سخت دراماتیک", labelEn: "Hard Dramatic" },
  ],
  shotType: [
    { id: "extreme_close_up", label: "کلوزآپ شدید", labelEn: "ECU", icon: SHOT_SIZE_ICONS.extreme_close_up },
    { id: "close_up", label: "کلوزآپ", labelEn: "CU", icon: SHOT_SIZE_ICONS.close_up },
    { id: "medium_close_up", label: "مدیوم کلوزآپ", labelEn: "MCU", icon: SHOT_SIZE_ICONS.medium_close_up },
    { id: "medium", label: "مدیوم", labelEn: "MS", icon: SHOT_SIZE_ICONS.medium },
    { id: "medium_wide", label: "مدیوم واید", labelEn: "MFS", icon: SHOT_SIZE_ICONS.medium_wide },
    { id: "wide", label: "واید", labelEn: "FS", icon: SHOT_SIZE_ICONS.wide },
    { id: "extreme_wide", label: "واید شدید", labelEn: "ELS", icon: SHOT_SIZE_ICONS.extreme_wide },
    { id: "establishing", label: "استابلیشینگ", labelEn: "LS", icon: SHOT_SIZE_ICONS.establishing },
    { id: "insert", label: "اینسرت", labelEn: "Insert", icon: SHOT_FRAMING_ICONS.insert },
    { id: "cutaway", label: "کات‌اوی", labelEn: "Cutaway", icon: SHOT_FRAMING_ICONS.cutaway },
    { id: "two_shot", label: "دو نفره", labelEn: "Two-Shot", icon: SHOT_FRAMING_ICONS.two_shot },
    { id: "over_shoulder", label: "اور شولدر", labelEn: "OTS", icon: SHOT_FRAMING_ICONS.over_shoulder },
  ],
  angle: [
    { id: "eye_level", label: "سطح چشم", labelEn: "Eye Level", icon: SHOT_ANGLE_ICONS.eye_level },
    { id: "high_angle", label: "زاویه بالا", labelEn: "High Angle", icon: SHOT_ANGLE_ICONS.high_angle },
    { id: "low_angle", label: "زاویه پایین", labelEn: "Low Angle", icon: SHOT_ANGLE_ICONS.low_angle },
    { id: "birds_eye", label: "چشم پرنده", labelEn: "Bird's Eye", icon: SHOT_ANGLE_ICONS.birds_eye },
    { id: "worms_eye", label: "چشم کرم", labelEn: "Worm's Eye", icon: SHOT_ANGLE_ICONS.worms_eye },
    { id: "dutch", label: "داچ", labelEn: "Dutch Angle", icon: SHOT_ANGLE_ICONS.dutch },
    { id: "pov", label: "دید اول شخص", labelEn: "POV", icon: SHOT_FRAMING_ICONS.pov },
    { id: "over_shoulder", label: "پشت شانه", labelEn: "Over Shoulder", icon: SHOT_FRAMING_ICONS.over_shoulder },
  ],
  movement: [
    { id: "static", label: "ثابت", labelEn: "Static", icon: CAMERA_MOVEMENT_ICONS.static },
    { id: "pan", label: "پن", labelEn: "Pan", icon: CAMERA_MOVEMENT_ICONS.pan },
    { id: "tilt", label: "تیلت", labelEn: "Tilt", icon: CAMERA_MOVEMENT_ICONS.tilt },
    { id: "dolly_in", label: "دالی جلو", labelEn: "Dolly In", icon: CAMERA_MOVEMENT_ICONS.dolly_in },
    { id: "dolly_out", label: "دالی عقب", labelEn: "Dolly Out", icon: CAMERA_MOVEMENT_ICONS.dolly_out },
    { id: "truck", label: "تراک", labelEn: "Truck", icon: CAMERA_MOVEMENT_ICONS.truck },
    { id: "crane", label: "جرثقیل", labelEn: "Crane", icon: CAMERA_MOVEMENT_ICONS.crane },
    { id: "handheld", label: "دستی", labelEn: "Handheld", icon: CAMERA_MOVEMENT_ICONS.handheld },
    { id: "steadicam", label: "استدی‌کم", labelEn: "Steadicam", icon: CAMERA_MOVEMENT_ICONS.steadicam },
    { id: "whip_pan", label: "ویپ پن", labelEn: "Whip Pan", icon: CAMERA_MOVEMENT_ICONS.whip_pan },
    { id: "zoom", label: "زوم", labelEn: "Zoom", icon: CAMERA_MOVEMENT_ICONS.zoom },
    { id: "push_in", label: "پوش این", labelEn: "Push In", icon: CAMERA_MOVEMENT_ICONS.push_in },
    { id: "pull_out", label: "پول اوت", labelEn: "Pull Out", icon: CAMERA_MOVEMENT_ICONS.pull_out },
    { id: "arc", label: "آرک", labelEn: "Arc", icon: CAMERA_MOVEMENT_ICONS.arc },
  ],
  focus: [
    { id: "deep_focus", label: "فوکوس عمیق", labelEn: "Deep Focus", icon: SHOT_FOCUS_ICONS.deep_focus },
    { id: "shallow_focus", label: "فوکوس کم‌عمق", labelEn: "Shallow Focus", icon: SHOT_FOCUS_ICONS.shallow_focus },
    { id: "soft_focus", label: "فوکوس نرم", labelEn: "Soft Focus", icon: SHOT_FOCUS_ICONS.soft_focus },
    { id: "tilt_shift_v", label: "تیلت‌شیفت عمودی", labelEn: "Tilt-Shift V", icon: SHOT_FOCUS_ICONS.tilt_shift_v },
    { id: "tilt_shift_h", label: "تیلت‌شیفت افقی", labelEn: "Tilt-Shift H", icon: SHOT_FOCUS_ICONS.tilt_shift_h },
  ],
  mechanism: [
    { id: "tripod", label: "سه‌پایه", labelEn: "Tripod", icon: CAMERA_MECHANISM_ICONS.tripod },
    { id: "handheld", label: "دستی", labelEn: "Handheld", icon: CAMERA_MECHANISM_ICONS.handheld },
    { id: "gimbal", label: "گیمبال", labelEn: "Gimbal", icon: CAMERA_MECHANISM_ICONS.gimbal },
    { id: "steadicam", label: "استدی‌کم", labelEn: "Steadicam", icon: CAMERA_MECHANISM_ICONS.steadicam },
    { id: "crane", label: "جرثقیل", labelEn: "Crane", icon: CAMERA_MECHANISM_ICONS.crane },
    { id: "drone", label: "درون", labelEn: "Drone", icon: CAMERA_MECHANISM_ICONS.drone },
  ],
} as const;

export const CAMERA_MODELS = [
  { id: "arri_alexa_mini_lf", label: "آری الکسا مینی LF", labelEn: "ARRI Alexa Mini LF", sensor: "Large Format", description: "سنسور بزرگ، رنگ‌های طبیعی عالی" },
  { id: "arri_alexa_35", label: "آری الکسا ۳۵", labelEn: "ARRI Alexa 35", sensor: "Super 35", description: "جدیدترین نسل آری" },
  { id: "red_v_raptor", label: "رد وی-رپتور", labelEn: "RED V-Raptor", sensor: "VV 8K", description: "رزولوشن بالا و دینامیک رنج وسیع" },
  { id: "red_komodo", label: "رد کومودو", labelEn: "RED Komodo", sensor: "Super 35 6K", description: "کامپکت و قدرتمند" },
  { id: "sony_venice_2", label: "سونی ونیز ۲", labelEn: "Sony Venice 2", sensor: "Full Frame 8.6K", description: "دوگانگی سنسور بزرگ و سوپر ۳۵" },
  { id: "sony_fx6", label: "سونی FX6", labelEn: "Sony FX6", sensor: "Full Frame", description: "سبک و حرفه‌ای" },
  { id: "blackmagic_ursa_g2", label: "بلک‌مجیک URSA G2", labelEn: "Blackmagic URSA Mini Pro G2", sensor: "Super 35", description: "مقرون‌به‌صرفه و حرفه‌ای" },
  { id: "blackmagic_pocket_6k", label: "بلک‌مجیک پاکت 6K", labelEn: "Blackmagic Pocket 6K", sensor: "Super 35", description: "کوچک و قابل حمل" },
  { id: "canon_c70", label: "کانن C70", labelEn: "Canon C70", sensor: "Super 35 DGO", description: "اتوفوکوس عالی" },
  { id: "canon_r5c", label: "کانن R5C", labelEn: "Canon R5C", sensor: "Full Frame 8K", description: "هیبرید عکس و فیلم" },
  { id: "panasonic_s1h", label: "پاناسونیک S1H", labelEn: "Panasonic S1H", sensor: "Full Frame", description: "ضبط نامحدود" },
  { id: "custom", label: "سفارشی", labelEn: "Custom", sensor: "", description: "دوربین دلخواه" },
] as const;

export const LENS_TYPES = [
  { id: "spherical", label: "اسفریکال", labelEn: "Spherical", description: "لنز استاندارد سینمایی" },
  { id: "anamorphic", label: "آنامورفیک", labelEn: "Anamorphic", description: "فلر و بوکه بیضوی، حس سینمایی" },
  { id: "vintage_anamorphic", label: "آنامورفیک وینتیج", labelEn: "Vintage Anamorphic", description: "فلرهای آبی/نارنجی، حس نوستالژیک" },
  { id: "vintage_spherical", label: "اسفریکال وینتیج", labelEn: "Vintage Spherical", description: "نرمی تصویر و کاراکتر خاص" },
  { id: "macro", label: "ماکرو", labelEn: "Macro", description: "فوکوس بسیار نزدیک" },
  { id: "tilt_shift", label: "تیلت-شیفت", labelEn: "Tilt-Shift", description: "کنترل پرسپکتیو و فوکوس" },
  { id: "fisheye", label: "فیش‌آی", labelEn: "Fisheye", description: "زاویه فوق‌العاده باز با اعوجاج" },
  { id: "custom", label: "سفارشی", labelEn: "Custom", description: "لنز دلخواه" },
] as const;

export const FOCAL_LENGTHS = [
  { id: "14mm", label: "۱۴mm", labelEn: "14mm", category: "ultra_wide", description: "فوق واید - منظره" },
  { id: "18mm", label: "۱۸mm", labelEn: "18mm", category: "ultra_wide", description: "فوق واید" },
  { id: "24mm", label: "۲۴mm", labelEn: "24mm", category: "wide", description: "واید - استابلیشینگ" },
  { id: "28mm", label: "۲۸mm", labelEn: "28mm", category: "wide", description: "واید - مستند" },
  { id: "35mm", label: "۳۵mm", labelEn: "35mm", category: "standard", description: "استاندارد - دید طبیعی" },
  { id: "40mm", label: "۴۰mm", labelEn: "40mm", category: "standard", description: "استاندارد" },
  { id: "50mm", label: "۵۰mm", labelEn: "50mm", category: "standard", description: "استاندارد - چشم انسان" },
  { id: "65mm", label: "۶۵mm", labelEn: "65mm", category: "medium_tele", description: "تله متوسط - پرتره" },
  { id: "85mm", label: "۸۵mm", labelEn: "85mm", category: "portrait", description: "پرتره - بوکه زیبا" },
  { id: "100mm", label: "۱۰۰mm", labelEn: "100mm", category: "portrait", description: "پرتره - فشردگی" },
  { id: "135mm", label: "۱۳۵mm", labelEn: "135mm", category: "tele", description: "تله - فشردگی زیاد" },
  { id: "200mm", label: "۲۰۰mm", labelEn: "200mm", category: "tele", description: "تله‌فتو - فاصله زیاد" },
  { id: "custom", label: "سفارشی", labelEn: "Custom", category: "custom", description: "فاصله کانونی دلخواه" },
] as const;

export const CINEMA_ASPECT_RATIOS = [
  { id: "2.39:1", label: "سینمااسکوپ (2.39:1)", labelEn: "CinemaScope 2.39:1", description: "فرمت واید سینمایی" },
  { id: "2.35:1", label: "سینمایی کلاسیک (2.35:1)", labelEn: "Classic Scope 2.35:1", description: "آنامورفیک کلاسیک" },
  { id: "1.85:1", label: "آکادمی فلت (1.85:1)", labelEn: "Academy Flat 1.85:1", description: "فرمت استاندارد سینما" },
  { id: "1.66:1", label: "اروپایی (1.66:1)", labelEn: "European 1.66:1", description: "فرمت اروپایی" },
  { id: "16:9", label: "تلویزیونی (16:9)", labelEn: "TV 16:9", description: "استاندارد تلویزیون/یوتیوب" },
  { id: "4:3", label: "کلاسیک (4:3)", labelEn: "Classic 4:3", description: "فرمت آکادمی کلاسیک" },
  { id: "1:1", label: "مربعی (1:1)", labelEn: "Square 1:1", description: "اینستاگرام" },
  { id: "9:16", label: "عمودی (9:16)", labelEn: "Vertical 9:16", description: "ریلز و استوری" },
  { id: "custom", label: "سفارشی", labelEn: "Custom", description: "نسبت تصویر دلخواه" },
] as const;

export const CINEMATOGRAPHY_TEMPLATES = [
  {
    id: "film_noir",
    label: "فیلم نوآر",
    labelEn: "Film Noir",
    description: "سیاه و سفید، سایه‌های دراماتیک، نور سخت",
    cameraModel: "arri_alexa_35" as CameraModel,
    lensType: "spherical" as LensType,
    focalLength: "35mm" as FocalLength,
    cinemaAspectRatio: "1.85:1" as CinemaAspectRatio,
    shotType: "medium" as ShotType,
    cameraAngle: "low_angle" as CameraAngle,
    cameraMovement: "static" as CameraMovement,
    keyLight: "chiaroscuro" as LightingPreset,
    colorGrade: "high contrast B&W, deep shadows, film grain",
  },
  {
    id: "neon_cyberpunk",
    label: "نئون سایبرپانک",
    labelEn: "Neon Cyberpunk",
    description: "نورهای نئون، رنگ‌های بنفش و آبی، فضای آینده‌نگرانه",
    cameraModel: "red_v_raptor" as CameraModel,
    lensType: "anamorphic" as LensType,
    focalLength: "40mm" as FocalLength,
    cinemaAspectRatio: "2.39:1" as CinemaAspectRatio,
    shotType: "wide" as ShotType,
    cameraAngle: "eye_level" as CameraAngle,
    cameraMovement: "steadicam" as CameraMovement,
    keyLight: "neon" as LightingPreset,
    colorGrade: "teal and purple, neon glow, high saturation",
  },
  {
    id: "golden_hour_drama",
    label: "ساعت طلایی دراماتیک",
    labelEn: "Golden Hour Drama",
    description: "نور طلایی غروب، فضای رمانتیک و دراماتیک",
    cameraModel: "arri_alexa_mini_lf" as CameraModel,
    lensType: "vintage_anamorphic" as LensType,
    focalLength: "85mm" as FocalLength,
    cinemaAspectRatio: "2.39:1" as CinemaAspectRatio,
    shotType: "close_up" as ShotType,
    cameraAngle: "eye_level" as CameraAngle,
    cameraMovement: "dolly_in" as CameraMovement,
    keyLight: "golden_hour" as LightingPreset,
    colorGrade: "warm golden tones, lens flare, soft highlights",
  },
  {
    id: "documentary_raw",
    label: "مستند خام",
    labelEn: "Documentary Raw",
    description: "واقع‌گرایانه، دوربین دستی، نور طبیعی",
    cameraModel: "sony_fx6" as CameraModel,
    lensType: "spherical" as LensType,
    focalLength: "24mm" as FocalLength,
    cinemaAspectRatio: "16:9" as CinemaAspectRatio,
    shotType: "medium" as ShotType,
    cameraAngle: "eye_level" as CameraAngle,
    cameraMovement: "handheld" as CameraMovement,
    keyLight: "natural" as LightingPreset,
    colorGrade: "natural, desaturated, documentary look",
  },
  {
    id: "epic_landscape",
    label: "منظره حماسی",
    labelEn: "Epic Landscape",
    description: "نمای واید حماسی، فضای عظیم و باشکوه",
    cameraModel: "red_v_raptor" as CameraModel,
    lensType: "spherical" as LensType,
    focalLength: "14mm" as FocalLength,
    cinemaAspectRatio: "2.39:1" as CinemaAspectRatio,
    shotType: "extreme_wide" as ShotType,
    cameraAngle: "birds_eye" as CameraAngle,
    cameraMovement: "crane" as CameraMovement,
    keyLight: "golden_hour" as LightingPreset,
    colorGrade: "vibrant, epic color grading, enhanced sky",
  },
  {
    id: "intimate_portrait",
    label: "پرتره صمیمی",
    labelEn: "Intimate Portrait",
    description: "کلوزآپ صمیمانه، بوکه زیبا، نور نرم",
    cameraModel: "arri_alexa_mini_lf" as CameraModel,
    lensType: "vintage_spherical" as LensType,
    focalLength: "85mm" as FocalLength,
    cinemaAspectRatio: "1.85:1" as CinemaAspectRatio,
    shotType: "close_up" as ShotType,
    cameraAngle: "eye_level" as CameraAngle,
    cameraMovement: "static" as CameraMovement,
    keyLight: "soft_diffused" as LightingPreset,
    colorGrade: "soft skin tones, creamy bokeh, warm highlights",
  },
  {
    id: "action_sequence",
    label: "سکانس اکشن",
    labelEn: "Action Sequence",
    description: "سریع، پویا، دوربین دستی",
    cameraModel: "red_komodo" as CameraModel,
    lensType: "spherical" as LensType,
    focalLength: "24mm" as FocalLength,
    cinemaAspectRatio: "2.39:1" as CinemaAspectRatio,
    shotType: "medium" as ShotType,
    cameraAngle: "low_angle" as CameraAngle,
    cameraMovement: "handheld" as CameraMovement,
    keyLight: "hard_dramatic" as LightingPreset,
    colorGrade: "desaturated, high contrast, bleach bypass",
  },
  {
    id: "horror_tension",
    label: "ترسناک تنش‌آمیز",
    labelEn: "Horror Tension",
    description: "تاریک، سایه‌های ترسناک، فضای وهم‌آلود",
    cameraModel: "arri_alexa_35" as CameraModel,
    lensType: "spherical" as LensType,
    focalLength: "28mm" as FocalLength,
    cinemaAspectRatio: "2.39:1" as CinemaAspectRatio,
    shotType: "medium" as ShotType,
    cameraAngle: "dutch" as CameraAngle,
    cameraMovement: "push_in" as CameraMovement,
    keyLight: "low_key" as LightingPreset,
    colorGrade: "cold blue-green, deep shadows, unsettling",
  },
  {
    id: "music_video_stylized",
    label: "موزیک ویدئو استایلیزه",
    labelEn: "Music Video Stylized",
    description: "رنگارنگ، استایلیزه، حرکات خلاقانه",
    cameraModel: "sony_venice_2" as CameraModel,
    lensType: "anamorphic" as LensType,
    focalLength: "50mm" as FocalLength,
    cinemaAspectRatio: "2.39:1" as CinemaAspectRatio,
    shotType: "medium" as ShotType,
    cameraAngle: "eye_level" as CameraAngle,
    cameraMovement: "arc" as CameraMovement,
    keyLight: "neon" as LightingPreset,
    colorGrade: "highly stylized, split toning, vibrant colors",
  },
  {
    id: "social_vertical",
    label: "شبکه اجتماعی عمودی",
    labelEn: "Social Media Vertical",
    description: "فرمت عمودی، نزدیک، انرژیک",
    cameraModel: "sony_fx6" as CameraModel,
    lensType: "spherical" as LensType,
    focalLength: "35mm" as FocalLength,
    cinemaAspectRatio: "9:16" as CinemaAspectRatio,
    shotType: "medium_close_up" as ShotType,
    cameraAngle: "eye_level" as CameraAngle,
    cameraMovement: "static" as CameraMovement,
    keyLight: "soft_diffused" as LightingPreset,
    colorGrade: "bright, clean, instagram-ready",
  },
] as const;

export const TIER_LIMITS = {
  free: { maxProjects: 1, maxShots: 10, llmModel: "openai/gpt-4o-mini", maxCredits: 50, label: "رایگان", labelEn: "Free" },
  pro: { maxProjects: 10, maxShots: 50, llmModel: "openai/gpt-4o-mini", maxCredits: 500, label: "حرفه‌ای", labelEn: "Pro" },
  studio: { maxProjects: -1, maxShots: -1, llmModel: "openai/gpt-4o-mini", maxCredits: 2000, label: "استودیو", labelEn: "Studio" },
  unlimited: { maxProjects: -1, maxShots: -1, llmModel: "openai/gpt-4o-mini", maxCredits: -1, label: "نامحدود", labelEn: "Unlimited" },
} as const;

export const ELEMENT_TYPES = [
  { id: "character", label: "شخصیت", labelEn: "Character", icon: "User" },
  { id: "location", label: "لوکیشن", labelEn: "Location", icon: "MapPin" },
  { id: "property", label: "آیتم/پراپ", labelEn: "Prop", icon: "Package" },
] as const;
